development:
  adapter: mysql2
  database: racuni
  username: root
  password: Dsalkjm!
  encoding: utf8 
  reconnect: true 
  
production:
  adapter: mysql2
  database: racuni
  username: root
  password: Dsalkjm!
  encoding: utf8 
  reconnect: true 
  