development:
  adapter: mysql
  database: nektar
  username: root
  password:
  encoding: UTF8
production:
  adapter: mysql
  database: nektar
  username: root
  password: 
  encoding: UTF8



#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
  
  
# PostgreSQL versions 7.4 - 8.1
#
# Get the C bindings:
#   gem install postgres
# or use the pure-Ruby bindings on Windows:
#   gem install postgres-pr
postgresql_example:
  adapter: postgresql
  database: trunk_development
  username: trunk
  password:

  # Connect on a TCP socket.  Omitted by default since the client uses a
  # domain socket that doesn't need configuration.
  #host: remote-database
  #port: 5432

  # Schema search path.  The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Character set encoding.  The server defaults to sql_ascii.
  #encoding: UTF8

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   info, notice, warning, error, log, fatal, or panic
  # The server defaults to notice.
  #min_messages: warning


# SQLite version 2.x
#   gem install sqlite-ruby
sqlite_example:
  adapter: sqlite
  database: db/development.sqlite2


# SQLite version 3.x
#   gem install sqlite3-ruby
sqlite3_example:
  adapter: sqlite3
  database: db/development.sqlite3


# In-memory SQLite 3 database.  Useful for tests.
sqlite3_in_memory_example:
  adapter: sqlite3
  database: ":memory:"
