development:
  adapter: mysql
  database: nektar
  username: root
  password:
  encoding: UTF8  
  
production:
  adapter: mysql
  database: racuni
  username: root
  password: Dsalkjm!
  encoding: UTF8